"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
import { ArtifactsTable } from "./ArtifactsTable";

interface ArtifactRow {
  artifact_id?: string;
  artifact_hash?: string;
  chain_valid?: boolean;
  verified?: boolean;
  isNew?: boolean;
  terms?: { price_usd_monthly?: number };
  policy_check?: { decision?: string };
  [key: string]: unknown;
}

interface LedgerRow {
  artifact:      Record<string, unknown>;
  verified:      boolean;
  artifact_hash: string;
  prev_hash:     string;
}

export function LedgerLive({ initialArtifacts }: { initialArtifacts: ArtifactRow[] }) {
  const [artifacts, setArtifacts] = useState<ArtifactRow[]>(initialArtifacts);
  const [live, setLive]           = useState(false);
  const lastHashRef = useRef<string>(
    initialArtifacts.at(-1)?.artifact_hash ?? "GENESIS"
  );

  useEffect(() => {
    const supabase = createClient();

    const channel = supabase
      .channel("ledger-live")
      .on(
        "postgres_changes",
        { event: "INSERT", schema: "public", table: "ledger" },
        (payload) => {
          const row = payload.new as LedgerRow;
          const newEntry: ArtifactRow = {
            ...(row.artifact as Record<string, unknown>),
            verified:      row.verified,
            artifact_hash: row.artifact_hash,
            chain_valid:   row.prev_hash === lastHashRef.current,
            isNew:         true,
          };
          lastHashRef.current = row.artifact_hash;
          setArtifacts((prev) => [...prev, newEntry]);

          // Remove flash after 2 s
          setTimeout(() => {
            setArtifacts((prev) =>
              prev.map((a) =>
                a.artifact_id === newEntry.artifact_id ? { ...a, isNew: false } : a
              )
            );
          }, 2000);
        }
      )
      .subscribe((status) => {
        if (status === "SUBSCRIBED") setLive(true);
      });

    return () => {
      supabase.removeChannel(channel);
    };
  }, []);

  // KPIs derived from live state
  const totalValue = artifacts.reduce(
    (sum, a) => sum + (a.terms?.price_usd_monthly ?? 0),
    0
  );
  const approved = artifacts.filter(
    (a) => a.policy_check?.decision === "APPROVED"
  ).length;

  return (
    <main className="px-6 py-16 max-w-7xl mx-auto">
      {/* Header */}
      <div className="mb-10 flex items-start justify-between">
        <div>
          <p
            className="text-xs font-mono tracking-widest uppercase mb-2"
            style={{ color: "#02f8c5" }}
          >
            AUDIT LEDGER
          </p>
          <h1 className="text-3xl font-black uppercase tracking-tight">
            AGENT DEAL LEDGER
          </h1>
          <p className="mt-2 text-sm" style={{ color: "#aaa" }}>
            CFO REVIEW — all contracts negotiated autonomously by AI agents.
            Requires human sign-off before payment is triggered.
          </p>
        </div>

        {live ? (
          <span
            className="text-xs font-mono tracking-widest px-4 py-2 border"
            style={{ borderColor: "#02f8c522", color: "#02f8c5" }}
          >
            <span className="animate-pulse">●</span> LIVE
          </span>
        ) : (
          <Link
            href="/ledger"
            className="text-xs font-mono tracking-widest px-4 py-2 border transition-colors"
            style={{ borderColor: "#333", color: "#888" }}
          >
            ↻ REFRESH
          </Link>
        )}
      </div>

      {/* KPI strip */}
      <div className="mb-8 grid grid-cols-3 gap-4">
        {[
          { label: "TOTAL DEALS",        value: artifacts.length },
          { label: "POLICY APPROVED",    value: approved },
          { label: "MONTHLY COMMITMENT", value: `$${totalValue.toLocaleString()} USD` },
        ].map(({ label, value }) => (
          <div
            key={label}
            className="px-5 py-4"
            style={{ border: "1px solid #1a1a1a", background: "#030303" }}
          >
            <p
              className="text-xs font-mono tracking-widest uppercase"
              style={{ color: "#888" }}
            >
              {label}
            </p>
            <p className="mt-2 text-2xl font-black tracking-tight">{value}</p>
          </div>
        ))}
      </div>

      {/* Table */}
      <ArtifactsTable
        artifacts={
          artifacts as unknown as Parameters<typeof ArtifactsTable>[0]["artifacts"]
        }
      />

      {/* Footer */}
      <p className="mt-5 text-xs font-mono" style={{ color: "#666" }}>
        SIGNED WITH Ed25519 · CHAIN: SHA-256 · SOURCE: Supabase ledger · GENERATED BY negotiate_deal.py
      </p>
    </main>
  );
}
