import { readFileSync, existsSync } from "fs";
import { join } from "path";
import { ArtifactsTable } from "../components/ArtifactsTable";
import { Nav } from "../components/Nav";
import Link from "next/link";

const ARTIFACTS_PATH = join(process.cwd(), "..", "artifacts.json");

function getArtifacts() {
  if (!existsSync(ARTIFACTS_PATH)) return [];
  try { return JSON.parse(readFileSync(ARTIFACTS_PATH, "utf-8")); }
  catch { return []; }
}

export default function LedgerPage() {
  const artifacts = getArtifacts();
  const totalValue = artifacts.reduce(
    (sum: number, a: { terms: { price_usd_monthly: number } }) =>
      sum + a.terms.price_usd_monthly,
    0
  );
  const approved = artifacts.filter(
    (a: { policy_check: { decision: string } }) => a.policy_check.decision === "APPROVED"
  ).length;

  return (
    <>
      <Nav />

      <main className="px-6 py-16 max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-10 flex items-start justify-between">
          <div>
            <p className="text-xs font-mono tracking-widest uppercase mb-2" style={{ color: "#02f8c5" }}>
              AUDIT LEDGER
            </p>
            <h1 className="text-3xl font-black uppercase tracking-tight">
              AGENT DEAL LEDGER
            </h1>
            <p className="mt-2 text-sm" style={{ color: "#aaa" }}>
              CFO REVIEW — all contracts negotiated autonomously by AI agents.
              Requires human sign-off before payment is triggered.
            </p>
          </div>
          <Link
            href="/ledger"
            className="text-xs font-mono tracking-widest px-4 py-2 border transition-colors"
            style={{ borderColor: "#333", color: "#888" }}
          >
            ↻ REFRESH
          </Link>
        </div>

        {/* KPI strip */}
        <div className="mb-8 grid grid-cols-3 gap-4">
          {[
            { label: "TOTAL DEALS", value: artifacts.length },
            { label: "POLICY APPROVED", value: approved },
            { label: "MONTHLY COMMITMENT", value: `$${totalValue.toLocaleString()} USD` },
          ].map(({ label, value }) => (
            <div
              key={label}
              className="px-5 py-4"
              style={{ border: "1px solid #1a1a1a", background: "#030303" }}
            >
              <p className="text-xs font-mono tracking-widest uppercase" style={{ color: "#888" }}>
                {label}
              </p>
              <p className="mt-2 text-2xl font-black tracking-tight">{value}</p>
            </div>
          ))}
        </div>

        {/* Table */}
        <ArtifactsTable artifacts={artifacts} />

        {/* Footer */}
        <p className="mt-5 text-xs font-mono" style={{ color: "#666" }}>
          SIGNED WITH HMAC-SHA256 · SOURCE: artifacts.json · GENERATED BY negotiate_deal.py
        </p>
      </main>
    </>
  );
}
