import { createClient } from "@/lib/supabase/server";
import { ArtifactsTable } from "../components/ArtifactsTable";
import { Nav } from "../components/Nav";
import Link from "next/link";

async function getArtifacts() {
  const supabase = await createClient();
  const { data } = await supabase
    .from("ledger")
    .select("artifact, verified, artifact_hash, prev_hash")
    .order("id", { ascending: true });
  if (!data) return [];
  return data.map((row, idx) => ({
    ...(row.artifact as Record<string, unknown>),
    verified:    row.verified,
    chain_valid: idx === 0
      ? row.prev_hash === "GENESIS"
      : row.prev_hash === data[idx - 1].artifact_hash,
  }));
}

export default async function LedgerPage() {
  const artifacts = await getArtifacts();
  const totalValue = artifacts.reduce(
    (sum: number, a: Record<string, unknown>) => {
      const terms = a.terms as { price_usd_monthly?: number } | undefined;
      return sum + (terms?.price_usd_monthly ?? 0);
    },
    0
  );
  const approved = artifacts.filter(
    (a: Record<string, unknown>) => {
      const pc = a.policy_check as { decision?: string } | undefined;
      return pc?.decision === "APPROVED";
    }
  ).length;

  return (
    <>
      <Nav />

      <main className="px-6 py-16 max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-10 flex items-start justify-between">
          <div>
            <p className="text-xs font-mono tracking-widest uppercase mb-2" style={{ color: "#02f8c5" }}>
              AUDIT LEDGER
            </p>
            <h1 className="text-3xl font-black uppercase tracking-tight">
              AGENT DEAL LEDGER
            </h1>
            <p className="mt-2 text-sm" style={{ color: "#aaa" }}>
              CFO REVIEW — all contracts negotiated autonomously by AI agents.
              Requires human sign-off before payment is triggered.
            </p>
          </div>
          <Link
            href="/ledger"
            className="text-xs font-mono tracking-widest px-4 py-2 border transition-colors"
            style={{ borderColor: "#333", color: "#888" }}
          >
            ↻ REFRESH
          </Link>
        </div>

        {/* KPI strip */}
        <div className="mb-8 grid grid-cols-3 gap-4">
          {[
            { label: "TOTAL DEALS", value: artifacts.length },
            { label: "POLICY APPROVED", value: approved },
            { label: "MONTHLY COMMITMENT", value: `$${totalValue.toLocaleString()} USD` },
          ].map(({ label, value }) => (
            <div
              key={label}
              className="px-5 py-4"
              style={{ border: "1px solid #1a1a1a", background: "#030303" }}
            >
              <p className="text-xs font-mono tracking-widest uppercase" style={{ color: "#888" }}>
                {label}
              </p>
              <p className="mt-2 text-2xl font-black tracking-tight">{value}</p>
            </div>
          ))}
        </div>

        {/* Table */}
        <ArtifactsTable artifacts={artifacts as Parameters<typeof ArtifactsTable>[0]["artifacts"]} />

        {/* Footer */}
        <p className="mt-5 text-xs font-mono" style={{ color: "#666" }}>
          SIGNED WITH Ed25519 · CHAIN: SHA-256 · SOURCE: Supabase ledger · GENERATED BY negotiate_deal.py
        </p>
      </main>
    </>
  );
}
